name: Halide LLVM Builder
on: push

jobs:
  build_llvm:
    name: Build llvm-${{matrix.llvm_version}}-${{matrix.bits}}-${{matrix.os}}
    runs-on: ${{matrix.os}}
    env:
      CC: ${{matrix.cc}}
      CXX: ${{matrix.cxx}}
      LD: ld

    strategy:
      fail-fast: true  # TODO # Keep running even if one job fails
      matrix:
        arch: [x86]
        bits: [32, 64]
        os: [windows-latest, ubuntu-18.04, macos-latest]
        llvm_version: [8, 9, 10, trunk]
        include:
          - llvm_version: 8
            llvm_branch: release/8.x
          - llvm_version: 9
            llvm_branch: release/9.x
          - llvm_version: 10
            llvm_branch: release/10.x
          - llvm_version: trunk
            llvm_branch: master

          - os: macos-latest
            cc: clang
          - os: macos-latest
            cxx: clang++

          - os: ubuntu-18.04
            cc: gcc
          - os: ubuntu-18.04
            cxx: g++

          - os: windows-latest
            cc: cl
          - os: windows-latest
            cxx: cl

        exclude:
          # We don't support 32-bit macos builds
          - os: macos-latest
            bits: 32

    steps:

    - name: Sniff Windows
      if: startsWith(matrix.os, 'windows')
      shell: bash
      run: |
        du -h -d 1 "C:/Program Files"

    - name: Configure Ubuntu-32
      if: startsWith(matrix.os, 'ubuntu') && matrix.bits == 32
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install gcc-multilib g++-multilib

    - name: Build llvm-${{matrix.llvm_version}}-${{matrix.bits}}-${{matrix.os}}
      shell: bash
      run: |
        set -eux

        # Demangle Windows names, to simplify CMake stuff later
        _ROOT=${GITHUB_WORKSPACE//\\//}

        LLVM_ID="llvm-${{matrix.llvm_version}}-${{matrix.arch}}-${{matrix.os}}-${{matrix.bits}}"
        LLVM_SOURCE_DIR="${_ROOT}/${LLVM_ID}-source"
        LLVM_BUILD_DIR="${_ROOT}/${LLVM_ID}-build"
        LLVM_INSTALL_DIR="${_ROOT}/${LLVM_ID}-install"
        LLVM_INSTALL_TGZ="${_ROOT}/${LLVM_ID}.tgz"
        LLVM_INSTALL_URL="https://buildbot.halide-lang.org/llvm/${LLVM_ID}.tgz"
        LLVM_COMMIT_HASH_FILE=".halide_builder_llvm_commit"

        # get the hash of the last llvm we built
        # by downloading the existing .tgz (if any)
        # and extracting the value from .halide_builder_llvm_commit.
        # (This isn't very efficient, but that's ok.)
        if curl --fail --user llvm_user:${{secrets.LLVM_USER_PASSWORD}} --output ${_ROOT}/old_llvm.tgz ${LLVM_INSTALL_URL}; then
          LLVM_OLD_COMMIT=`tar -O -xf ${_ROOT}/old_llvm.tgz "./${LLVM_COMMIT_HASH_FILE}"`
        else
          LLVM_OLD_COMMIT=bogus
        fi
        rm -rf ${_ROOT}/old_llvm.tgz

        echo "LLVM_OLD_COMMIT is ${LLVM_OLD_COMMIT}"

        # Clone current top of tree.
        git clone https://github.com/llvm/llvm-project.git \
          "${LLVM_SOURCE_DIR}" \
          --branch ${{matrix.llvm_branch}} \
          --single-branch \
          --depth 1

        # Find the new commit.
        cd ${LLVM_SOURCE_DIR}
        LLVM_NEW_COMMIT=`git rev-parse HEAD`

        echo "LLVM_NEW_COMMIT is ${LLVM_NEW_COMMIT}"

        if [ ${LLVM_NEW_COMMIT} == ${LLVM_OLD_COMMIT} ]; then
          echo "LLVM is already up to date, no need to rebuild"
        else
          echo "LLVM needs rebuilding!"

          LLVM_BUILD_32_BITS=$([ ${{matrix.bits}} == 32 ] && echo "ON" || echo "OFF")

          CMAKE_GEN="Ninja"
          EXTRA_DEFS=
          PARALLEL_JOBS=4

          if [[ ${{matrix.os}} == windows* ]]; then
            # Windows VMs don't have enough RAM to build more than this
            # concurrently (will fail to compile intermittently)
            PARALLEL_JOBS=3
            EXTRA_DEFS="-A x64 -T host=x64"
            # CMAKE_GEN="Visual Studio 16"
          fi

          if [[ ${{matrix.os}} == ubuntu* && ${{matrix.bits}} == 32 ]]; then
            EXTRA_DEFS="-D CMAKE_FIND_ROOT_PATH=/usr/lib/i386-linux-gnu -D CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY"
            export CC="${CC} -m32 "
            export CXX="${CXX} -m32 "
            export LD="${LD} -melf_i386 "
          fi

          if [[ ${{matrix.os}} == macos* ]]; then
            EXTRA_DEFS="-D LLVM_ENABLE_SUPPORT_XCODE_SIGNPOSTS=FORCE_OFF"
          fi

          # To conserve limited disk space, we disable as many nonessential
          # targets as possible when configuring
          # TODO: add WebAssembly for trunk
          # TODO: LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN is evil
          cmake \
            -D CMAKE_BUILD_TYPE=Release \
            -D CMAKE_INSTALL_PREFIX="${LLVM_INSTALL_DIR}" \
            -D LLVM_BUILD_32_BITS=${LLVM_BUILD_32_BITS} \
            -D LLVM_BUILD_BENCHMARKS=OFF \
            -D LLVM_BUILD_EXAMPLES=OFF \
            -D LLVM_BUILD_TESTS=OFF \
            -D LLVM_ENABLE_ASSERTIONS=ON \
            -D LLVM_ENABLE_DIA_SDK=OFF \
            -D LLVM_ENABLE_EH=OFF \
            -D LLVM_ENABLE_PROJECTS="clang;lld" \
            -D LLVM_ENABLE_RTTI=ON \
            -D LLVM_ENABLE_TERMINFO=OFF \
            -D LLVM_INCLUDE_BENCHMARKS=OFF \
            -D LLVM_INCLUDE_EXAMPLES=OFF \
            -D LLVM_INCLUDE_TESTS=OFF \
            -D LLVM_INSTALL_TOOLCHAIN_ONLY=ON \
            -D LLVM_TARGETS_TO_BUILD="X86;ARM;NVPTX;AArch64;Mips;PowerPC;Hexagon" \
            -D LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=ON \
            -G "${CMAKE_GEN}" \
            ${EXTRA_DEFS} \
            -B "${LLVM_BUILD_DIR}" \
            -S "${LLVM_SOURCE_DIR}/llvm"

          cmake \
            --build "${LLVM_BUILD_DIR}" \
            -j ${PARALLEL_JOBS} \
            --target install

          # du -h -d 2 ${LLVM_BUILD_DIR}
          # du -h -d 2 ${LLVM_INSTALL_DIR}

          echo ${LLVM_NEW_COMMIT} > ${LLVM_INSTALL_DIR}/${LLVM_COMMIT_HASH_FILE}

          cd ${LLVM_INSTALL_DIR}
          tar -czf ${LLVM_INSTALL_TGZ} .

          curl \
            --upload-file ${LLVM_INSTALL_TGZ} \
            --user llvm_user:${{secrets.LLVM_USER_PASSWORD}} \
            ${LLVM_INSTALL_URL}

        fi

    - name: Report llvm-${{matrix.llvm_version}}-${{matrix.bits}}-${{matrix.os}}
      if: failure()
      shell: bash
      run: |
        set -eux

        # Demangle Windows names, to simplify CMake stuff later
        _ROOT=${GITHUB_WORKSPACE//\\//}

        LLVM_ID="llvm-${{matrix.llvm_version}}-${{matrix.arch}}-${{matrix.os}}-${{matrix.bits}}"
        LLVM_SOURCE_DIR="${_ROOT}/${LLVM_ID}-source"
        LLVM_BUILD_DIR="${_ROOT}/${LLVM_ID}-build"
        LLVM_INSTALL_DIR="${_ROOT}/${LLVM_ID}-install"

        echo LLVM_SOURCE_DIR
        du -h -d 2 ${LLVM_SOURCE_DIR}

        echo LLVM_BUILD_DIR
        du -h -d 2 ${LLVM_BUILD_DIR}

        # echo LLVM_INSTALL_DIR
        # du -h -d 2 ${LLVM_INSTALL_DIR}
